### ISSUE TITLE
Date Forgery

### ISSUE THREAD

**Issue by codingfrombrazil** [pflaeging/PortableSigner2#14]
I've made a experience, I've set up a VM with a date in the past, let's say months ago, and sign a pdf with PortableSigner2.

And I've looked at the certificate info in the last page of the PDF and there it was, the date in the past, as if I've signed that document a month ago.

Is there something I could do to verify if someone did the same with a PDF? And prove they did something just like set the clock of a machine on the past and then signed the pdf?

**Comment by codingfrombrazil** [comment]
ping @pflaeging

**Comment by pflaeging** [comment]
Hi, sorry for answering so late!

Yes, that's true. The normal signing of PDF's (and PortableSigner does this) relies on the local clock of the device (PC, server, you name it) 

That's the price for working complete offline (there's no internet connection for signing required)

There would be the possibility to incorporate digital signed time services, but I haven't the time to implement it. 

Some volunteers? ;-)
