### ISSUE TITLE
Can portablesigner be used with a smart card?

### ISSUE THREAD

**Issue by petterreinholdtsen** [pflaeging/PortableSigner2#6]
Is using a smart card for the signing supported by portablesigner?

**Comment by SmartLayer** [comment]
No. Portable Signer only supports the use of a p12 file with private key in it. The use of smart-card requires a different keystore type (PKCS11). Feel feel to update the title to "request adding the feature of using smart card". Shouldn't be too hard though.

**Comment by pflaeging** [comment]
Thx for the correct answer. Establishment of a smart-card is more complex, ...

Do you mean only a smart card with keystore? Or a real smartcard with signature processor? And very much of the signature cards don't support PKCS11, they are highly proprietary, ...
